sudo: false
language: node_js
node_js:
  - "10"
cache: npm


stages:
  - cache
  - eslint
  - build
  - name: github deploy
    if: tag IS present

jobs:
  include:
    - stage: cache
      script: true

    - stage: eslint
      install: true
      script: npm run eslint

    - stage: build
      install: true
      script: npm run build

    - stage: github deploy
      install: true
      script:
        - echo "Deploying to GitHub releases ..."
        - npm run build
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file:
          - bin/dungeon-revealer-linux
          - bin/dungeon-revealer-macos
          - bin/dungeon-revealer-win.exe
        skip_cleanup: true
        draft: true
        on:
          tags: true
