name: Build Docker

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:
  build_branch:
    name: Deploy dev
    if: startsWith(github.ref, 'refs/heads/') # Just the branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: apclary/dungeon-revealer
          tags: dev,latest
          tag_with_ref: true
          tag_with_sha: true

  build_tag:
    name: Deploy release
    if: startsWith(github.ref, 'refs/tags/') # Just the tags
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: apclary/dungeon-revealer
          tags: release,stable,latest
          tag_with_ref: true
          tag_with_sha: true
